config/routes.rb
Rails.application.routes.draw do

  get '/books', to: 'books#index'
  get '/pages/home', to: 'pages#home', as: "home"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = ["Pragmatic Programmer", "Eloquent Ruby", "Secrets of the JavaScript Ninja"]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/books/index.html.erb
<h1>Libros</h1>

<table border="1">
  <thead>
    <tr>
      <th>Nombre</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p> <%= link_to "Ir al Home", home_path%> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Books</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<!-- <h1>En cinco años tendrás <%= params[:age].to_i + 5 %> años</h1>
El "query string" es el conjunto de propiedades que van después del signo de interrogación (?) de un URL. Rails automáticamente convierte las propiedades en el hash params que puedes acceder desde el controlador o la vista.
Por ejemplo
http://localhost:3000/?age=30.
Los datos del metodo o actuador se modifican o controla desde la URL-->

<h1>
  Estas en la parte de /pages/home
</h1>

<p> <%= link_to "Ir al Books", books_path%> </p>